
services:
  messenger:
    build:
      context: .
      dockerfile: Messenger/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=messengerdb;Username=postgres;Password=postgres;
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres

  postgres:
    image: postgres:15  
    container_name: messagedb-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messengerdb
    ports:
      - "5432:5432"  
    